### ISSUE TITLE
Alignment issue in Header.

### ISSUE THREAD

**Issue by zerefwayne** [opencodeiiita/Opencode-Collaborative-19#118]
![image](https://user-images.githubusercontent.com/28949397/51084668-bf41dd80-1753-11e9-8c18-8089cd21f886.png)

Center align these items.

**Comment by B3ingALearner** [comment]
@opencodebot claim

**Comment by B3ingALearner** [comment]
@opencodebot claim

**Comment by prjmaurya** [comment]
@opencodebot claim

**Comment by anupm12** [comment]
@opencodebot claim

**Comment by ankichd11** [comment]
can i work on this

**Comment by neerajd007** [comment]
@opencodebot claim

**Comment by Jahanvi21** [comment]
@opencodebot claim

**Comment by kavi-12** [comment]
@opencodebot claim

**Comment by kavi-12** [comment]
@opencodebot claim

**Comment by B3ingALearner** [comment]
@opencodebot unclaim

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
can I work on this issue opencodebot bec no link to accept is there in the mail

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by ShipraGaur** [comment]
@opencodebot claim

**Comment by thenullterminator** [comment]
@opencodebot claim

**Comment by thenullterminator** [comment]
@opencodebot claim

**Comment by BLJS2warchief** [comment]
@opencodebot claim

**Comment by BLJS2warchief** [comment]
@opencodebot unclaim

**Comment by anupm12** [comment]
@opencodebot claim

**Comment by jishansingh** [comment]
@opencodebot claim

**Comment by anupm12** [comment]
@ananya-agrawal I had earlier claimed this issue and also completed working on it but as my participant entry PR was not merged I was waiting for it to be merged but meanwhile, I was unassigned from this issue.
Please assign it to me.

**Comment by vishnuk7** [comment]
@opencodebot claim
