### ISSUE TITLE
Add styling to the headings.

### ISSUE THREAD

**Issue by Ace-Bansal** [opencodeiiita/Opencode-Collaborative-19#13]
The headings in question are 'Participants', 'Mentors' and 'Projects'.
Center them and increase their size as well.

**Comment by ujjwal-batra** [comment]
i want to work on it

**Comment by Ace-Bansal** [comment]
Sure. Go ahead.

**Comment by chi50800** [comment]
i also want to work on it

**Comment by Jahanvi21** [comment]
i wanna work on it too!

**Comment by Ace-Bansal** [comment]
@chi50800 @Jahanvi21 This issue can't be assigned to you at this point of time. @ujjwal-batra commented first, so he gets the issue. Try looking at the other issues.

**Comment by Ace-Bansal** [comment]
Also please solve issue #1 'Add yourselves to the participants section' first.

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by palak2001** [comment]
@opencodebot claim
