### ISSUE TITLE
Fix participants.json 

### ISSUE THREAD

**Issue by prateek76** [opencodeiiita/Opencode-Collaborative-19#149]
There is a bug in json file,particpants cards are not being displayed

**Comment by Rattlecode17sh** [comment]
@opencodebot claim

**Comment by prateek76** [comment]
This issue is no longer needed open it again if bugs appears again and @Rattlecode17sh should be assigned for this issue

**Comment by coding-clown** [comment]
is this issue solved

**Comment by prateek76** [comment]
> is this issue solved

no
