### ISSUE TITLE
Make cards for participants.

### ISSUE THREAD

**Issue by Ace-Bansal** [opencodeiiita/Opencode-Collaborative-19#15]
The participants should be displayed in a separate card.
![cards](https://user-images.githubusercontent.com/34866483/51070888-add2d580-166e-11e9-823b-0ee310e401ed.jpg)
Take a look at these cards for reference.

**Comment by zerefwayne** [comment]
You can use Bootstrap 4 cards.

**Comment by mohammed-adil** [comment]
@opencodebot claim

**Comment by mohammed-adil** [comment]
@Ace-Bansal The participants are already displayed in squares (I think so), I only have to make a card container for it right?

**Comment by Ace-Bansal** [comment]
Make a card container. Style it to display the info in a structured manner. Display the social links of the participants as well.

**Comment by mohammed-adil** [comment]
ok, I'll do it than

**Comment by Ace-Bansal** [comment]
Assigned to @mohammed-adil

**Comment by mohammed-adil** [comment]
Hey @Ace-Bansal can i use font-awesome library for social-media icons?

**Comment by Ace-Bansal** [comment]
Sure

**Comment by mohammed-adil** [comment]
@Ace-Bansal One more thing what about the people who didn't add their social media links?(like me😅)
Should i add js condition for it?

**Comment by zerefwayne** [comment]
@mohammed-adil That would be great. Go ahead :+1:

**Comment by mohammed-adil** [comment]
Hey @zerefwayne I can't write an if statement within a variable!
What i see is a single variable(participantDiv) is used to represent the data of a participant, and within that variable I'm unable to execute a if condition.
I have designed the UI tho, have a look at it in screen shot.
![pic](https://user-images.githubusercontent.com/31363829/51073801-49c70600-169c-11e9-970b-f6aed8edd5de.png)

There's a bit hover effect for links. Plus people have uploaded image of different sizes (what to do about them?).

**Comment by mohammed-adil** [comment]
@Ace-Bansal @zerefwayne anyone??

**Comment by zerefwayne** [comment]
@mohammed-adil The design is fine. You won't be able to write a condition in a variable. Use some javascript function to do that job for you. What do you actually want to do?

**Comment by mohammed-adil** [comment]
It wasn't asked in the issue!, but wanted to create a method that will not display social media links if tit isn't provided by participants.
