### ISSUE TITLE
Make cards for mentors.

### ISSUE THREAD

**Issue by Ace-Bansal** [opencodeiiita/Opencode-Collaborative-19#16]
The mentors should be displayed in separate cards.
![cards](https://user-images.githubusercontent.com/34866483/51070932-8defe180-166f-11e9-82ce-2f4f575e698f.jpg)
Take a look at these cards for reference.
You may use use Bootstrap 4 cards.

**Comment by mohammed-adil** [comment]
@opencodebot claim

**Comment by parag1201** [comment]
@opencodebot claim

**Comment by Ace-Bansal** [comment]
@mohammed-adil already has an issue assigned to him. @nucelya this one's been assigned to you.

**Comment by orichamaru** [comment]
@opencodebot claim

**Comment by orichamaru** [comment]
@opencodebot

**Comment by orichamaru** [comment]
@opencodebot claim

**Comment by helios1101** [comment]
Is this issue fixed? Can I work on this issue?
@opencodebot claim

**Comment by helios1101** [comment]
@Ace-Bansal  Can I try this issue?

**Comment by anupm12** [comment]
@Ace-Bansal can you assign this issue to me?

**Comment by sourabh1031** [comment]
@prateek76 i will take this issue

**Comment by ananya-agrawal** [comment]
Closing this issue for now as the issue is not clear about what to do
