### ISSUE TITLE
Change design of the hero image.

### ISSUE THREAD

**Issue by zerefwayne** [opencodeiiita/Opencode-Collaborative-19#2]
![image](https://user-images.githubusercontent.com/28949397/51070119-a48f3c00-1661-11e9-9cac-d476c8309192.png)

This doesn't look good right now. Try to make the design better.

**Comment by Archies11** [comment]
@opencodebot claim

**Comment by Archies11** [comment]
@zerefwayne Sir, I am not sure how should I proceed, which platform to be precise to edit this image. Please help me out.

**Comment by zerefwayne** [comment]
@Archies11 Add a background image to the container and change the text to make it look better. You've to just modify the HTML and CSS.

**Comment by Archies11** [comment]
@zerefwayne Okay, thank you sir.

**Comment by coding-clown** [comment]
help me where the submit code for this issue. I am new to Github and opensource

**Comment by palak2001** [comment]
@opencodebot claim

**Comment by palak2001** [comment]
![opencode](https://user-images.githubusercontent.com/44226699/51079194-eb744480-16e8-11e9-8e1c-31d0481db5f4.jpg)

**Comment by palak2001** [comment]
@opencodebot claim

**Comment by Adadysgirl** [comment]
@opencodebot  claim

**Comment by neerajd007** [comment]
@opencodebot claim

**Comment by neerajd007** [comment]
@opencodebot claim

**Comment by parag1201** [comment]
@opencodebot claim

**Comment by Archies11** [comment]
Sir, this issue was assigned to me yesterday. I am not sure if it can be reassigned to someone else within the same day. Is the issue still mine?Or am i allowed to claim another issue? @zerefwayne

**Comment by zerefwayne** [comment]
@Archies11 You can take up another issue once you've got PR merged for previous one.

@parag1201 @neerajd007 @Adadysgirl @coding-clown This issue had already been assigned to @Archies11 Please do not try to claim issues if you see they have already been assigned to someone else.Further such offences might start fetching you negative points and will affect your leaderboard positions.

**Comment by coding-clown** [comment]
is this issue given to me or to @Archies11 
can i work on this . it is showing that i was assigned this
