### ISSUE TITLE
Compress images of participants, mentors, and projects 

### ISSUE THREAD

**Issue by ananya-agrawal** [opencodeiiita/Opencode-Collaborative-19#202]
Present website is getting too slow, compress all the images of mentor, participants and projects

**Comment by neerajd007** [comment]
@opencodebot claim

**Comment by neerajd007** [comment]
@opencodebot unclaim

**Comment by anupm12** [comment]
@opencodebot claim

**Comment by pradeepgangwar** [comment]
@ananya-agrawal @anupm12 This is not worth 30 points. I have reduced the points to 20. Please take care while uploading the score. 
Closing this via #218
