### ISSUE TITLE
Make cards in projects section uniform

### ISSUE THREAD

**Issue by Jigar3** [opencodeiiita/Opencode-Collaborative-19#242]
Cards in participants and mentor section are uniform throughout, make the same for projects section

**Comment by vishnuk7** [comment]
@opencodebot claim

**Comment by vishnuk7** [comment]
@Jigar3  please close this issue

**Comment by vishnuk7** [comment]
@ananya-agrawal please close this issue

**Comment by vishnuk7** [comment]
@ananya-agrawal  this issue is already merged, please close this issue
