### ISSUE TITLE
Make total number of forks and stars visible on the website

### ISSUE THREAD

**Issue by Jigar3** [opencodeiiita/Opencode-Collaborative-19#243]

**Comment by kumarshubham707** [comment]
@opencodebot claim

**Comment by kumarshubham707** [comment]
@opencodebot claim

**Comment by kumarshubham707** [comment]
@opencodebot unclaim

**Comment by vishnuk7** [comment]
@opencodebot claim

**Comment by vishnuk7** [comment]
@opencodebot claim

**Comment by vishnuk7** [comment]
@Jigar3  @pradeepgangwar it was informed in slack that we can take upto 3 issues simultaneously but the bot is not allowing to claim....please assign this issue to me....

**Comment by Jigar3** [comment]
@vishnuk7 Assigning you the issue

**Comment by Rattlecode17sh** [comment]
Let me know if this issue still remains open

**Comment by vishnuk7** [comment]
@Rattlecode17sh I am still working on this issue

**Comment by Jigar3** [comment]
@vishnuk7 What's the status?
