### ISSUE TITLE
Add a favicon 

### ISSUE THREAD

**Issue by Jigar3** [opencodeiiita/Opencode-Collaborative-19#244]

**Comment by sa4k5hi** [comment]
@opencodebot claim

**Comment by Jigar3** [comment]
What is the status of this issue?? @sa4k5hi

**Comment by ashish4321** [comment]
@sa4k5hi are you working on it?

**Comment by anupm12** [comment]
@Jigar3 can you assign to me if @sa4k5hi is not working?

**Comment by Jigar3** [comment]
@anupm12 You could have this issue if she doesn't reply by morning

**Comment by anupm12** [comment]
Ok.

**Comment by ashish4321** [comment]
@Jigar3 i asked for working on it prior to @anupm12

**Comment by ashish4321** [comment]
My comment is 6 mins earlier than @anupm12. I should be allowed to work on it @Jigar3

**Comment by Jigar3** [comment]
I didn't see your comment. @anupm12 let @ashish4321 work on it then

**Comment by ashish4321** [comment]
@Jigar3 thanks

**Comment by ashish4321** [comment]
@Jigar3 Please review the PR for favicon
