### ISSUE TITLE
Make the navbar fixed while scrolling

### ISSUE THREAD

**Issue by Jigar3** [opencodeiiita/Opencode-Collaborative-19#247]

**Comment by sa4k5hi** [comment]
@opencodebot claim

**Comment by Jigar3** [comment]
@ujjwal-batra I think there is some error over here by the bot, this issue is assigned to @sa4k5hi .

**Comment by ujjwal-batra** [comment]
@jigar3 np sir 👍🏻

**Comment by anupm12** [comment]
@Jigar3 can you assign this issue to me if this issue is still open?

**Comment by Rattlecode17sh** [comment]
@opencodebot claim

**Comment by Rattlecode17sh** [comment]
Let me know this if this issue still remains open @Jigar3

**Comment by anupm12** [comment]
@sa4k5hi are you still working on this??

**Comment by anupm12** [comment]
@Jigar3 please assign this to me

**Comment by Jigar3** [comment]
As @Rattlecode17sh commented first he is assigned to this issue.

**Comment by anupm12** [comment]
> @Jigar3 can you assign this issue to me if this issue is still open?

@Jigar3 I commented 2 hours before him
