### ISSUE TITLE
Embed the OpenCode19 Trailer in the website

### ISSUE THREAD

**Issue by Jigar3** [opencodeiiita/Opencode-Collaborative-19#248]
Make a link in the navbar titled trailer, on clicking it a modal should open which plays the opencode trailer
https://www.facebook.com/opencodeiiita/videos/2301796573173119/

**Comment by deepakDOTexe** [comment]
@opencodebot claim

**Comment by anupm12** [comment]
can I do this?

**Comment by thenullterminator** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
@ananya-agrawal can I take the issue bec no response from assignee
