### ISSUE TITLE
Toggle switch for a night mode

### ISSUE THREAD

**Issue by Jigar3** [opencodeiiita/Opencode-Collaborative-19#249]

**Comment by anupm12** [comment]
I completed working on this but my other PR is still open @Jigar3

**Comment by Jigar3** [comment]
No problem. Submit a new PR from a seperate branch

**Comment by anupm12** [comment]
@Jigar3 can you please tell me how?

> No problem. Submit a new PR from a seperate branch

**Comment by Jigar3** [comment]
@anupm12 just create a new branch. 
do `git reset HEAD~<no of commits to go back>`
This command will take you back to a previous commit, edit in that and send a new PR from that branch

**Comment by anupm12** [comment]
@Jigar3 ok.
My PR #229  which solves issue #58 is not yet reviewed, I opened it before 4 days.

**Comment by anupm12** [comment]
Live link https://opencode-night-mode.netlify.com
