### ISSUE TITLE
Make a countdown timer

### ISSUE THREAD

**Issue by Jigar3** [opencodeiiita/Opencode-Collaborative-19#262]
Make a countdown timer which ends on last date of OpenCode'19 (12th Feb). Place it on the landing page

**Comment by devgupta2607** [comment]
@opencodebot claim

**Comment by devgupta2607** [comment]
@opencodebot claim

**Comment by Rattlecode17sh** [comment]
Let me know if this issue still remains open

**Comment by Jigar3** [comment]
Make it big and place on the landing page image

**Comment by devgupta2607** [comment]
![sample pic](https://user-images.githubusercontent.com/42816087/51638479-71fc1200-1f84-11e9-8a55-32f1095bd083.png)

I have made like this but I cannot decide what design I can add. Can you help @Jigar3 ?
Changes to be made pls mention them.

**Comment by Jigar3** [comment]
Just send a PR, other mentors can suggest changes

**Comment by devgupta2607** [comment]
How can I create the github pages of a branch of my repository? The document says we can create link of master branch only but I am making changes in a seperate branch.

**Comment by devgupta2607** [comment]
I have solved the question asked and added an pull request with an active link.

**Comment by anupm12** [comment]
Is this issue available for everyone?? @Jigar3 @prateek76 @pradeepgangwar @ananya-agrawal @zerefwayne
