### ISSUE TITLE
Fix Broken participant image.

### ISSUE THREAD

**Issue by Anupam-dagar** [opencodeiiita/Opencode-Collaborative-19#27]
![opencode 2019 collaborative 12-01-2019 15-04-44](https://user-images.githubusercontent.com/21174572/51071702-6c94f280-167b-11e9-954a-90875d33a650.png)

The image is broken. It needs to be fixed.

**Comment by zerefwayne** [comment]
@parag1201 Assigned to you.

**Comment by Anupam-dagar** [comment]
@parag1201 closing this as it is a duplicate of #24.
