### ISSUE TITLE
Implement typing animation on hello world text in landing page 

### ISSUE THREAD

**Issue by prateek76** [opencodeiiita/Opencode-Collaborative-19#271]

**Comment by punisher1151** [comment]
@anupam12 could you let me try for it as I am a beginner and want to do this

**Comment by prateek76** [comment]
@punisher1151 how may issues have you solved till now?

**Comment by punisher1151** [comment]
1 which i solved other got assigned to someone else

**Comment by prateek76** [comment]
@punisher1151 i am opening an issue claim that
