### ISSUE TITLE
Make drop down menu for responsive mobile devices

### ISSUE THREAD

**Issue by prateek76** [opencodeiiita/Opencode-Collaborative-19#272]
![whatsapp image 2019-01-25 at 12 48 53 am](https://user-images.githubusercontent.com/33982495/51703045-5b64c200-203b-11e9-9fe3-8ded78049968.jpeg)

it's not responsive
also add some horizontal padding to opencode logo and hamburger icon

**Comment by vishnuk7** [comment]
@opencodebot claim
