### ISSUE TITLE
Add zulip chat link in readme

### ISSUE THREAD

**Issue by ananya-agrawal** [opencodeiiita/Opencode-Collaborative-19#286]
Currently there is only slack channel link in readme, add zulip chat link also in readme

**Comment by anupm12** [comment]
@opencodebot claim

**Comment by anupm12** [comment]
@opencodebot unclaim

**Comment by vishnuk7** [comment]
@opencodebot claim

**Comment by ananya-agrawal** [comment]
@vishnuk7 these kind of issues have very less work to do so get them done at the earliest possible :sweat_smile:

**Comment by pradeepgangwar** [comment]
Fixed in #305
