### ISSUE TITLE
When viewed in mobile view text goes out of the cards. 

### ISSUE THREAD

**Issue by Rattlecode17sh** [opencodeiiita/Opencode-Collaborative-19#287]
![screenshot 45](https://user-images.githubusercontent.com/38866385/51803050-73745580-2276-11e9-9d67-3dcf988c649f.png)

**Comment by anupm12** [comment]
@opencodebot claim

**Comment by anupm12** [comment]
@Rattlecode17sh @ananya-agrawal how many points for this issue?

**Comment by ananya-agrawal** [comment]
@anupm12 updated :)
