### ISSUE TITLE
update participants.json

### ISSUE THREAD

**Issue by HGOYAL015** [opencodeiiita/Opencode-Collaborative-19#289]
update participants.json

_Originally posted by @HGOYAL015 in https://github.com/opencodeiiita/Opencode-Collaborative-19/pull/281#issuecomment-458047851_

**Comment by ananya-agrawal** [comment]
@HGOYAL015 why did you open this issue?

**Comment by HGOYAL015** [comment]
Mam It gets opened by mistake
And I try to delete but i wasn't able to do it .
