### ISSUE TITLE
Compress all the images

### ISSUE THREAD

**Issue by ananya-agrawal** [opencodeiiita/Opencode-Collaborative-19#290]
Presently the site is getting too slow mainly due to presence of lots of images. Compress all the images of participants, mentors, projects

**Comment by deepakDOTexe** [comment]
@opencodebot claim

**Comment by thenullterminator** [comment]
@opencodebot claim

**Comment by ananya-agrawal** [comment]
@deepakDOTexe please get this issue done at the earliest possible

**Comment by deepakDOTexe** [comment]
@ananya-agrawal All the images are of 30 MB approximately. Please let me know by how much you want me to reduce their size.

**Comment by deepakDOTexe** [comment]
@opencodebot unclaim

**Comment by thenullterminator** [comment]
@opencodebot claim

**Comment by ananya-agrawal** [comment]
@thenullterminator did you start working on this?

**Comment by thenullterminator** [comment]
Yes.....
