### ISSUE TITLE
Add a default quote on cards without having one, on flipping

### ISSUE THREAD

**Issue by punisher1151** [opencodeiiita/Opencode-Collaborative-19#297]
like "Talk is cheap. Show me the code" or any other

**Comment by punisher1151** [comment]
@opencodebot  claim

**Comment by prateek76** [comment]
start working after making the claim

**Comment by sourabh1031** [comment]
@prateek76 even though @punisher1151 made command to claim the issue but issue is still not assigned to him. is it a bug in opencodebot

**Comment by prateek76** [comment]
> @prateek76 even though @punisher1151 made command to claim the issue but issue is still not assigned to him. is it a bug in opencodebot

yes, there can be,you can open an issue in openbot repository regarding this

**Comment by palak2001** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
pull request reference #315
