### ISSUE TITLE
Images of few participants is not being displayed

### ISSUE THREAD

**Issue by anupm12** [opencodeiiita/Opencode-Collaborative-19#298]
Images of few participants are in the participant images folder but they are not being displayed.

**Comment by sourabh1031** [comment]
@opencodebot claim

**Comment by sourabh1031** [comment]
@anupm12  can you please tell me the name of the participants whose images are not visible . it will be quite waste of time to look into each url as the participants are in a greater number

**Comment by anupm12** [comment]
@sourabh1031 I don't remember....I'm sorry
