### ISSUE TITLE
Add links in the header to navigate to Participants, Mentors and Projects sections of the page.

### ISSUE THREAD

**Issue by zerefwayne** [opencodeiiita/Opencode-Collaborative-19#3]

**Comment by Archies11** [comment]
@opencodebot claim

**Comment by zerefwayne** [comment]
@Archies11 You cannot claim two issues at a time. Please go through the contribution guidelines first.

**Comment by devgupta2607** [comment]
@opencodebot claim

**Comment by thesmallstar** [comment]
@opencodebot claim

**Comment by zerefwayne** [comment]
@thesmallstar Please don't try to claim an issue already assigned to someone else.

**Comment by devgupta2607** [comment]
Added a PR for this issue @zerefwayne

**Comment by pradeepgangwar** [comment]
@zerefwayne Why u closed this issue?
