### ISSUE TITLE
star and fork Blowrage repository 

### ISSUE THREAD

**Issue by prateek76** [opencodeiiita/Opencode-Collaborative-19#300]
post fork link and a screenshot to gain points
repo - https://github.com/prateek76/Blowrage2

**Comment by Rattlecode17sh** [comment]
![screenshot 57](https://user-images.githubusercontent.com/38866385/51849660-35466700-2346-11e9-91df-50086bad522f.png)

**Comment by thenullterminator** [comment]
![screenshot from 2019-01-28 21-46-39](https://user-images.githubusercontent.com/46654914/51849689-4000fc00-2346-11e9-8e4f-5f778ac469df.png)

**Comment by anupm12** [comment]
Done

![image](https://user-images.githubusercontent.com/35293695/51852629-7e011e80-234c-11e9-8f6b-98131f816dcc.png)

**Comment by anupm12** [comment]
Done

![image](https://user-images.githubusercontent.com/35293695/51852714-a557eb80-234c-11e9-987c-44635046f70d.png)

**Comment by punisher1151** [comment]
![blowrage](https://user-images.githubusercontent.com/42278252/51853215-bd7c3a80-234d-11e9-9dd2-2977aa503b47.png)

**Comment by KaushalSahu** [comment]
![screenshot from 2019-01-28 23-13-40](https://user-images.githubusercontent.com/15705036/51855139-7c3a5980-2352-11e9-89fe-1b4b3c378601.png)

**Comment by HGOYAL015** [comment]
**DONE**
![Uploading image.png…]()

**Comment by chi50800** [comment]
![repo ss](https://user-images.githubusercontent.com/42766836/51893806-fd820280-23cb-11e9-8ee4-e53497c80e2b.jpg)

**Comment by deepakDOTexe** [comment]
Done
![screenshot from 2019-01-29 15-48-42](https://user-images.githubusercontent.com/46655706/51901337-69b93200-23dd-11e9-9d5a-305c9800aba0.png)

**Comment by dhairyabaweja** [comment]
https://github.com/dhairyabaweja/Blowrage2

![openc](https://user-images.githubusercontent.com/34601019/51925750-c0daf900-2415-11e9-964d-99635e21522d.PNG)

**Comment by ashish4321** [comment]
![screenshot 2019-01-30 at 21 48 35](https://user-images.githubusercontent.com/25305613/51995530-e54bd980-24d8-11e9-8a02-f4b75bfdfc2f.png)

**Comment by vishnuk7** [comment]
done
![image](https://user-images.githubusercontent.com/31013847/52051649-2ba54500-257a-11e9-997e-01d261b2b1e6.png)

**Comment by neerajd007** [comment]
fork link : https://github.com/neerajd007/Blowrage2
![screenshot from 2019-02-01 17-59-36](https://user-images.githubusercontent.com/44533403/52123172-47c4e700-264b-11e9-89ae-b2734aba6294.png)

**Comment by shivhek25** [comment]
![screenshot 2019-02-02 at 10 37 25 am](https://user-images.githubusercontent.com/24766191/52160185-94093900-26d6-11e9-9733-76623ffe7c34.png)

**Comment by pradeepgangwar** [comment]
No points will be allocated for this.
