### ISSUE TITLE
Add hover effects on links in navbar

### ISSUE THREAD

**Issue by devgupta2607** [opencodeiiita/Opencode-Collaborative-19#302]

**Comment by devgupta2607** [comment]
@opencodebot claim

**Comment by HGOYAL015** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
@ananya-agrawal @zerefwayne if @devgupta2607 is busy can I work on this

**Comment by devgupta2607** [comment]
I am working on it

**Comment by devgupta2607** [comment]
![hover effect](https://user-images.githubusercontent.com/42816087/51999286-6490db80-24e0-11e9-80f3-cccfb3b717e4.png)
Is the color and shape ok ?

**Comment by ananya-agrawal** [comment]
@devgupta2607 just make them either change color to blue or bold on hover, keep it simple.
From next time make a pr and then ask for reviews, it is much easier for us to review in that way
