### ISSUE TITLE
If a description is not present of a participant, show a default text "No description available."

### ISSUE THREAD

**Issue by zerefwayne** [opencodeiiita/Opencode-Collaborative-19#309]
![image](https://user-images.githubusercontent.com/28949397/51884013-86d50d00-23ab-11e9-962a-b206d6beb5eb.png)

**Comment by punisher1151** [comment]
@zerefwayne  the issue was already opened previously
Duplicate of 297#

**Comment by zerefwayne** [comment]
@punisher1151 Thanks. Closing this issue.
