### ISSUE TITLE
Disable the scroll while preloader is visible.

### ISSUE THREAD

**Issue by zerefwayne** [opencodeiiita/Opencode-Collaborative-19#312]
![image](https://user-images.githubusercontent.com/28949397/51884591-f1874800-23ad-11e9-94f5-9fce37e25d14.png)

**Comment by HGOYAL015** [comment]
@opencodebot claim

**Comment by sourabh1031** [comment]
@zerefwayne if @HGOYAL015 is busy then i will take up the issue

**Comment by pradeepgangwar** [comment]
reassigning due to inactivity.
