### ISSUE TITLE
Install rebound news chrome extension also star and fork the repo

### ISSUE THREAD

**Issue by prateek76** [opencodeiiita/Opencode-Collaborative-19#325]
link - https://chrome.google.com/webstore/detail/news-extension/anpknlfmlopfgmodgmnflnpjnfcklipa
repo link - https://github.com/prateek76/Rebound-Chrome-Extension

Attach proper screenshots to get points

**Comment by anupm12** [comment]
@opencodebot claim

**Comment by anupm12** [comment]
Done
![image](https://user-images.githubusercontent.com/35293695/52053172-abcda980-257e-11e9-93b7-9a487a8da25f.png)

**Comment by Rattlecode17sh** [comment]
![screenshot 61](https://user-images.githubusercontent.com/38866385/52067340-68843280-25a0-11e9-8852-9b77d782b898.png)
![screenshot 62](https://user-images.githubusercontent.com/38866385/52067341-68843280-25a0-11e9-83f4-3211b9d11240.png)

**Comment by shivhek25** [comment]
![image](https://user-images.githubusercontent.com/24766191/52160242-b94a7700-26d7-11e9-8b65-d348e79a74e6.png)
![image](https://user-images.githubusercontent.com/24766191/52160243-bea7c180-26d7-11e9-8778-61f30a6fc921.png)

**Comment by neerajd007** [comment]
Done!! 
![screenshot from 2019-02-02 11-08-42](https://user-images.githubusercontent.com/44533403/52160420-201d5f80-26db-11e9-8009-8571e2eaa3cc.png)
![screenshot from 2019-02-02 11-09-22](https://user-images.githubusercontent.com/44533403/52160421-201d5f80-26db-11e9-8c30-c2a4206aede4.png)
![screenshot from 2019-02-02 11-09-30](https://user-images.githubusercontent.com/44533403/52160423-20b5f600-26db-11e9-96cf-7cb893302ce5.png)

**Comment by pradeepgangwar** [comment]
No points will be allocated for this.
