### ISSUE TITLE
Image size is not in same ratio in mobile view for project cards

### ISSUE THREAD

**Issue by Rattlecode17sh** [opencodeiiita/Opencode-Collaborative-19#338]
![screenshot_2019-01-29-04-24-25-622](https://user-images.githubusercontent.com/38866385/52155178-6d7fd980-26a7-11e9-9916-b4664233d0ae.jpeg)

**Comment by Rattlecode17sh** [comment]
@opencodebot claim

**Comment by Rattlecode17sh** [comment]
@ananya-agrawal please assign the marks for this issue

**Comment by neerajd007** [comment]
@opencodebot claim
