### ISSUE TITLE
Make cards for participant's games

### ISSUE THREAD

**Issue by ananya-agrawal** [opencodeiiita/Opencode-Collaborative-19#342]
Make a new section for participant's games and add all the games made in #204 in cards under the section.
A parallel issue to add all the games in the json file is opened so the one working on the issue need not to add all the games in the json also. 
Link to json file for games: https://github.com/opencodeiiita/Opencode-Collaborative-19/blob/master/data/games.json

**Comment by anupm12** [comment]
@opencodebot claim

**Comment by HGOYAL015** [comment]
@opencodebot claim

**Comment by anupm12** [comment]
So I must wait for @thenullterminator to complete #343

**Comment by anupm12** [comment]
Please be quick @thenullterminator 
I see that you have taken 2 days for a Rookie issue.
It's a request.

**Comment by thenullterminator** [comment]
I am Dhairya Patel(gender:male)

**Comment by thenullterminator** [comment]
😭

**Comment by thenullterminator** [comment]
🧔🧔

**Comment by ananya-agrawal** [comment]
@thenullterminator haha sorry for that
