### ISSUE TITLE
Add personal website field to participant.json cards and display it 

### ISSUE THREAD

**Issue by ananya-agrawal** [opencodeiiita/Opencode-Collaborative-19#345]
Take the personal websites made in issue #206 and display them.
Add another icon for the website along with the fb, github and twitter icon 
![screenshot from 2019-02-02 19-26-29](https://user-images.githubusercontent.com/33188930/52164981-7660c180-2720-11e9-8925-462006ac7b3c.png)

**Comment by anupm12** [comment]
@opencodebot claim

**Comment by HGOYAL015** [comment]
@opencodebot claim
