### ISSUE TITLE
Create a landing page.

### ISSUE THREAD

**Issue by Anupam-dagar** [opencodeiiita/Opencode-Collaborative-19#35]
The current landing page looks too plain. Make an aesthetic looking landing page for the website.
Do a google search for good looking landing pages. For reference, take a look at https://opencodeiiita.github.io
![opencode 2019 collaborative 12-01-2019 16-30-49](https://user-images.githubusercontent.com/21174572/51072477-70c70d00-1687-11e9-8580-6966f525e2b2.png)

**Comment by mohammed-adil** [comment]
@opencodebot claim

**Comment by Anupam-dagar** [comment]
@mohammed-adil assigned.
Feel free to discuss over design in the issue comments.

**Comment by Anupam-dagar** [comment]
@zerefwayne let both of them exist, the title of #2 makes it a minor issue of changing the text and adding an image, this serves as a complete makeover for the landing page. This issue might take a little time while #2 will be a quick fix.

**Comment by mohammed-adil** [comment]
@zerefwayne @Anupam-dagar I can do the whole page in a day or two!
Need some suggestions though!
Any reference i should look into?

**Comment by zerefwayne** [comment]
Decide a good color scheme (I'll suggest using a flat color scheme) first, and a font (OpenSans). And then redesign the page by tweaking CSS properties. Look at some landing page examples for guidance.

**Comment by mohammed-adil** [comment]
ok i'll look into it

**Comment by Anupam-dagar** [comment]
@mohammed-adil It will be good if you can look for some ideas online and ask a review on them.
you can also take a look at idea given by @zerefwayne

**Comment by Anupam-dagar** [comment]
this issue shouldn't affect those components. they can be done separately by other participants.

**Comment by mohammed-adil** [comment]
Hey @Anupam-dagar @zerefwayne Did the header section, let me know what you guys think.
![pic](https://user-images.githubusercontent.com/31363829/51085397-4300c780-175e-11e9-888f-e4a560d7add3.png)

How are the colors? and do you think i should make two column grid for header section with one column containing text and a button and another SVG illustration?

**Comment by vishnuk7** [comment]
@opencodebot claim

**Comment by Anupam-dagar** [comment]
@mohammed-adil can you provide the live link for your repo so that I can test out the design rather than inspecting the screenshot.

**Comment by Anupam-dagar** [comment]
@vishnuk7 this issue is already in progress, please look for another one.

**Comment by mohammed-adil** [comment]
> 
> 
> @mohammed-adil can you provide the live link for your repo so that I can test out the design rather than inspecting the screenshot.

@Anupam-dagar  Here's the link: https://mohammed-adil.github.io/Opencode-Collaborative-19/index.html

**Comment by vishnuk7** [comment]
@opencodebot claim

**Comment by nucelya** [comment]
@opencodebot  claim

**Comment by pradeepgangwar** [comment]
@vishnuk7 @nucelya You guys cannot claim the issue when someone has a open PR and is already working on it. Please be careful and see issue comments before commenting. You can claim the issue if assignee does not open PR in 3 days not before that.
I will have to close your PR as a duplicate as this is violation of COC. I will be closing #180 by @vishnuk7 . Vishnu you can open PR again with better design after if #162 by @mohammed-adil  gets merged.
@Anupam-dagar  @zerefwayne  @ananya-agrawal  @aswinzz @Tlazypanda FYI. Please take note.

**Comment by palak2001** [comment]
The issue was assigned 2 days past, can I claim it now?

**Comment by pradeepgangwar** [comment]
@palak2001 this issue was not stale. there was a open PR #162  which has been merged now.
