### ISSUE TITLE
Ribbon covers the hamburger menu and responsiveness fix

### ISSUE THREAD

**Issue by anupm12** [opencodeiiita/Opencode-Collaborative-19#359]
![image](https://user-images.githubusercontent.com/35293695/52231478-157fe780-28e0-11e9-9d58-4a52f9df291b.png)

Issue approved by @ananya-agrawal

**Comment by anupm12** [comment]
@opencodebot claim

**Comment by anupm12** [comment]
@ananya-agrawal @prateek76 Please add labels.

**Comment by thenullterminator** [comment]
@opencodebot claim
