### ISSUE TITLE
Resize Cards

### ISSUE THREAD

**Issue by Jigar3** [opencodeiiita/Opencode-Collaborative-19#362]
The aspect ratio of every card is not eye pleasing. Make changes so it feels even and good

**Comment by neerajd007** [comment]
@opencodebot claim

**Comment by sourabh1031** [comment]
@pradeepgangwar please assign this to me if @neerajd007 is not able to do so

**Comment by sourabh1031** [comment]
@ananya-agrawal @pradeepgangwar @prateek76 please assign it to me

**Comment by Rattlecode17sh** [comment]
Sorry @sourabh1031 i never saw your comment and just made a PR for this issue and after watching your comments i closed my PR. Can i solve this as i am almost done with this issue. And if you want to give it a chance than no problem

**Comment by sourabh1031** [comment]
@Rattlecode17sh np :) . you can reopen your pr from my side but please do ask mentors because you solved issue without claiming it
