### ISSUE TITLE
Fix images of participant cards in mobile view. 

### ISSUE THREAD

**Issue by Rattlecode17sh** [opencodeiiita/Opencode-Collaborative-19#368]
![screenshot 86](https://user-images.githubusercontent.com/38866385/52351800-73800c80-2a51-11e9-8be9-3eb778f862cc.png)
![screenshot 85](https://user-images.githubusercontent.com/38866385/52351803-74b13980-2a51-11e9-87ee-42dd8d0b09e2.png)

Aspect ratio of few participants in mobile view is not uniform. Make it uniform so that it looks good

**Comment by Rattlecode17sh** [comment]
@opencodebot claim

**Comment by sourabh1031** [comment]
@Rattlecode17sh can you please close this issue as i have this in my pr as guided by @prateek76  
https://github.com/opencodeiiita/Opencode-Collaborative-19/pull/367

**Comment by sourabh1031** [comment]
@prateek76 @ananya-agrawal @pradeepgangwar please give your consent over this issue

**Comment by Rattlecode17sh** [comment]
I am closing this Issue @sourabh1031 . I never saw that issue so i am sorry
