### ISSUE TITLE
Fix competitive coding project card title.

### ISSUE THREAD

**Issue by Anupam-dagar** [opencodeiiita/Opencode-Collaborative-19#38]
The text is coming as technical writing for competitive coding repo.
![opencode 2019 collaborative 12-01-2019 18-11-30](https://user-images.githubusercontent.com/21174572/51073354-9529e600-1695-11e9-8a12-abb0d2d7159e.png)

**Comment by Rattlecode17sh** [comment]
i want to take this issue

**Comment by Rattlecode17sh** [comment]
@opencodebot claim

**Comment by Anupam-dagar** [comment]
complete in [#39](https://github.com/opencodeiiita/Opencode-Collaborative-19/pull/39)
