### ISSUE TITLE
Add Pull Request Template

### ISSUE THREAD

**Issue by pradeepgangwar** [opencodeiiita/Opencode-Collaborative-19#4]
Add pull request template for this repository. For more information on how to do this refer [this](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/).

**Comment by Archies11** [comment]
@openbot claim

**Comment by zerefwayne** [comment]
@Archies11 Please make a PR for the first issue that you've claimed. This issue can be claimed.

**Comment by manigedit** [comment]
@opencodebot  claim

**Comment by Anupam-dagar** [comment]
@manigedit Please make a Pull Request for your commit.

**Comment by manigedit** [comment]
@Anupam-dagar  Please review

**Comment by pradeepgangwar** [comment]
@manigedit Please make a pull request for your commit. If you don't know how to create a pull request read this https://help.github.com/articles/creating-a-pull-request/

**Comment by Kartik2301** [comment]
@opencodebot claim

**Comment by KaushalSahu** [comment]
@opencodebot claim

**Comment by KaushalSahu** [comment]
@opencodebot claim
