### ISSUE TITLE
Make participant cards flipped on click

### ISSUE THREAD

**Issue by ananya-agrawal** [opencodeiiita/Opencode-Collaborative-19#57]
Add "about" to come on the backside of card when flipped

**Comment by Rattlecode17sh** [comment]
@opencodebot  claim

**Comment by Rattlecode17sh** [comment]
@ananya-agrawal  i want to solve this issue

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by nucelya** [comment]
@opencodebot claim

**Comment by ankichd11** [comment]
i want to work on this

**Comment by ananya-agrawal** [comment]
Issue is assigned to @Rattlecode17sh

**Comment by parag1201** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by Rattlecode17sh** [comment]
Can i get some more time??.. I am working on it just one more day

**Comment by vishnuk7** [comment]
@opencodebot claim

**Comment by ananya-agrawal** [comment]
@vishnuk7, @Rattlecode17sh is having an active pr for the issue. Please find some other issue to work on.

**Comment by pradeepgangwar** [comment]
@Rattlecode17sh Your previous PR contains a lot of insignificant changes that broke the overall design of the website. Please recreate a Pull Request.

**Comment by vishnuk7** [comment]
@opencodebot claim

**Comment by Rattlecode17sh** [comment]
Okay i will do it again

**Comment by Rattlecode17sh** [comment]
@pradeepgangwar what changes are required??

**Comment by pradeepgangwar** [comment]
@Rattlecode17sh Your previous PR deleted some of the code part that was done in other PRs. Just make sure your PR contains the changes that are relevant to you and does not delete other code parts.

**Comment by Rattlecode17sh** [comment]
Okay give me some time.

**Comment by Rattlecode17sh** [comment]
@pradeepgangwar check it now

**Comment by pradeepgangwar** [comment]
fixed in #233
