### ISSUE TITLE
Sort participants name in alphabetic order

### ISSUE THREAD

**Issue by ananya-agrawal** [opencodeiiita/Opencode-Collaborative-19#60]
The names in json is increasing. When displayed show them alphabetically

**Comment by littleprodigy** [comment]
Claim

**Comment by littleprodigy** [comment]
@ananya-agrawal I want to solve

**Comment by aswinzz** [comment]
@littleprodigy you can work on it

**Comment by chiillax** [comment]
@opencodebot claim

**Comment by NamanDeept** [comment]
@opencodebot  claim and true

**Comment by techac** [comment]
@opencodebot claim

**Comment by vishnuk7** [comment]
@opencodebot claim

**Comment by sourabh1031** [comment]
@opencodebot claim

**Comment by Rattlecode17sh** [comment]
Let me know if this issue still remains open
