### ISSUE TITLE
Fix : Image size of participants (not of proper size) 

### ISSUE THREAD

**Issue by punisher1151** [opencodeiiita/Opencode-Collaborative-19#63]

**Comment by parag1201** [comment]
@opencodebot claim

**Comment by techac** [comment]
@punisher1151 participants images are fine what you exactly want.

**Comment by dhairyabaweja** [comment]
@opencodebot claim

**Comment by dhairyabaweja** [comment]
@punisher1151 Can I work on this issue?

**Comment by dhairyabaweja** [comment]
@opencodebot claim

**Comment by ananya-agrawal** [comment]
@punisher1151 @zerefwayne what is planned to be exactly done in this issue?

**Comment by kavi-12** [comment]
@opencodebot claim

**Comment by sourabh1031** [comment]
@ananya-agrawal can you please assign it to me

**Comment by ananya-agrawal** [comment]
@sourabh1031 I had myself asked the same question above :sweat_smile:

**Comment by ananya-agrawal** [comment]
Closing the issue as it is not clear in what to do
