### ISSUE TITLE
Add all the projects to the Projects section on the page.

### ISSUE THREAD

**Issue by zerefwayne** [opencodeiiita/Opencode-Collaborative-19#7]
Add the projects in projects.json in the correct format.

You can find the projects managed by Team OpenCode here : https://github.com/opencodeiiita
You can find the projects here : https://opencodeiiita.github.io/#works

**Comment by Jaggu-123** [comment]
@zerefwayne I will do this

**Comment by KeshavSharma21099** [comment]
@opencodebot claim

**Comment by KeshavSharma21099** [comment]
@opencodebot claim

**Comment by palak2001** [comment]
@opencodebot claim

**Comment by ananya-agrawal** [comment]
this issue is assigned to @Jaggu-123 . @palak2001 @KeshavSharma21099  please check above comments before trying to claim any issue
