### ISSUE TITLE
Add opencode logo to the website 

### ISSUE THREAD

**Issue by ananya-agrawal** [opencodeiiita/Opencode-Collaborative-19#8]

**Comment by ayush638** [comment]
Can I work on this issue

**Comment by pradeepgangwar** [comment]
Assigned to @ayush638

**Comment by punisher1151** [comment]
my username is changed to punisher1151 can you reassign me the same job  @pradeepgangwar

**Comment by punisher1151** [comment]
logo should be placed in navbar or anywhere else

**Comment by pradeepgangwar** [comment]
In navbar

**Comment by punisher1151** [comment]
@pradeepgangwar I have some proposed changes please review it
![screenshot from 2019-01-12 21-37-06](https://user-images.githubusercontent.com/42278252/51075544-cb299300-16b2-11e9-8cc7-cf1d5050abd5.png)
![screenshot from 2019-01-12 21-36-46](https://user-images.githubusercontent.com/42278252/51075545-cb299300-16b2-11e9-8a55-9a96bff7cab6.png)

**Comment by pradeepgangwar** [comment]
@punisher1151 Please make a PR we will discuss there.

**Comment by itsnkm2000** [comment]
can i take this issue?

**Comment by itsnkm2000** [comment]
@opencodebot claim
