### ISSUE TITLE
Add a scroll-to-top button in the footer.

### ISSUE THREAD

**Issue by zerefwayne** [opencodeiiita/Opencode-Collaborative-19#85]

**Comment by ashish4321** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
@zerefwayne
@Anupam-dagar 
@pradeepgangwar 
@ananya-agrawal 
 I suggested this issue in comment box but it is published in your name ?

**Comment by Anupam-dagar** [comment]
@punisher1151 keep a note of it while adding points. Add 10 points for it. Won't happen again. :smiley:

**Comment by punisher1151** [comment]
thnx

**Comment by punisher1151** [comment]
@Anupam-dagar i ve created a previous issue directly of image size would its points be added

**Comment by ananya-agrawal** [comment]
@ashish4321 you may proceed to work on this

**Comment by ananya-agrawal** [comment]
@punisher1151 the method we will be following is:
1. Comment issue on the thread
2. If approved by any of the mentor then open the issue yourself
3. Mentors will add points and label to it

**Comment by ashish4321** [comment]
@ananya-agrawal  I have added a pr for the issue. Pls check it
