### ISSUE TITLE
Add pagination to participants and projects section.

### ISSUE THREAD

**Issue by zerefwayne** [opencodeiiita/Opencode-Collaborative-19#86]
12 participants on one page would be preferrable.

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
@zerefwayne can i work on this issue

**Comment by Ace-Bansal** [comment]
You may proceed if you don't have any other issue assigned to you in this repo.

**Comment by lo0oper** [comment]
i want to claim this

**Comment by lo0oper** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
> You may proceed if you don't have any other issue assigned to you in this repo.

@ok i will do it

**Comment by lo0oper** [comment]
yeah this is my first issue , on opencode. i have claimed it now ,right?

**Comment by lo0oper** [comment]
okay . this is my first issue on open code .

**Comment by ananya-agrawal** [comment]
Issue is assigned to @punisher1151

**Comment by lo0oper** [comment]
fine i will look for some other issue.

**Comment by punisher1151** [comment]
I've made a basic pagination for project section but I need more time to figure out the js part.Please give some more time
![screenshot from 2019-01-14 16-20-22](https://user-images.githubusercontent.com/42278252/51108923-a1d74700-1819-11e9-8b1b-bf669acf2745.png)

**Comment by punisher1151** [comment]
@ananya-agrawal please assign this anyone else

**Comment by anupm12** [comment]
@opencodebot claim

**Comment by ananya-agrawal** [comment]
@punisher1151 any updates?

**Comment by Rattlecode17sh** [comment]
Let me solve this if still this issue is open

**Comment by anupm12** [comment]
@ananya-agrawal can I start working on this?
However, this issue is assigned to me and there is no update from @punisher1151

**Comment by anupm12** [comment]
@opencodebot unclaim

**Comment by vishnuk7** [comment]
@opencodebot unclaim

**Comment by vishnuk7** [comment]
@opencodebot claim
