### ISSUE TITLE
Add mentors to the website

### ISSUE THREAD

**Issue by ananya-agrawal** [opencodeiiita/Opencode-Collaborative-19#9]
Add all the mentors present in the organisation to data/mentors.json
projects under opencode org can be found here: [opencode](https://github.com/opencodeiiita)

**Comment by sourabh1031** [comment]
I would like to take this

**Comment by sourabh1031** [comment]
@opencodebot claim

**Comment by sourabh1031** [comment]
@opencodebot claim

**Comment by sourabh1031** [comment]
@ananya-agrawal it is better to keep the issue remain open because there are currently only 3 people in the list. I am sending a pr without mentioning closes #issue_number. Please tell me is it okay

**Comment by ananya-agrawal** [comment]
@sourabh1031 no worries, we will add mentors ourselves.
