### ISSUE TITLE
Logo of opencode is not visible due to colour of Nav-Bar

### ISSUE THREAD

**Issue by B3ingALearner** [opencodeiiita/Opencode-Collaborative-19#94]

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
can I work on this issue

**Comment by sourabh1031** [comment]
@punisher1151 please solve one issue at a time you are claiming more than one issue and it does give the opportunity to others to contribute

**Comment by punisher1151** [comment]
@sourabh1031 but they were already assigned so I've not got them except one

**Comment by zerefwayne** [comment]
@punisher1151 Accept the invitation link sent to your email.

**Comment by punisher1151** [comment]
@punisher1151

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by punisher1151** [comment]
@opencodebot claim

**Comment by sourabh1031** [comment]
@punisher1151 please check your email. accept the invitation from opencodebot and then claim the issue

**Comment by punisher1151** [comment]
@zerefwayne no link is present  to accept in the mail

**Comment by punisher1151** [comment]
![screenshot from 2019-01-13 19-14-30](https://user-images.githubusercontent.com/42278252/51086156-f1116f00-1768-11e9-90fe-24bbcabd0866.png)
![screenshot from 2019-01-13 19-14-15](https://user-images.githubusercontent.com/42278252/51086157-f1116f00-1768-11e9-8492-e13cbf7137bd.png)
![screenshot from 2019-01-13 19-14-03](https://user-images.githubusercontent.com/42278252/51086159-f1116f00-1768-11e9-9aa4-7cabf992a94a.png)
![screenshot from 2019-01-13 19-13-21](https://user-images.githubusercontent.com/42278252/51086160-f2429c00-1768-11e9-9fb2-29be1d6eb1aa.png)
![screenshot from 2019-01-13 15-19-29](https://user-images.githubusercontent.com/42278252/51086161-f2db3280-1768-11e9-962e-3c9e4e2281a4.png)
![screenshot from 2019-01-13 15-19-13](https://user-images.githubusercontent.com/42278252/51086162-f2db3280-1768-11e9-9c92-5e22174ebaca.png)
@zerefwayne I've tried to find suitable colors to make the logo visible but I think better color combination could be found after merge of landing page

**Comment by prateek76** [comment]
@zerefwayne there is a problem with @punisher1151 he is not getting issues on openbot claim, Have a look
